---
- name: <r_yum_repos_t_epel_repo> template a file to /etc/yum.repos.d/epel.repo
  template:
    src: epel.repo
    dest: /etc/yum.repos.d/epel.repo
    owner: root
    group: root
    mode: "0644"
    #validate:
    #backup: yes
